In [48]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [49]:
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [50]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [51]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [52]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [53]:
df['smoker'].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [54]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [55]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [56]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='str')

In [57]:
X=df[['tip', 'sex','day', 'time', 'size', 'total_bill']]
y=df['smoker']

In [58]:
X.head()

    tip     sex  day    time  size  total_bill
0  1.01  Female  Sun  Dinner     2       16.99
1  1.66    Male  Sun  Dinner     3       10.34
2  3.50    Male  Sun  Dinner     3       21.01
3  3.31    Male  Sun  Dinner     2       23.68
4  3.61  Female  Sun  Dinner     4       24.59

In [59]:
y

0       No
1       No
2       No
3       No
4       No
      ...
239     No
240    Yes
241    Yes
242     No
243     No
Name: smoker, Length: 244, dtype: category
Categories (2, str): ['Yes', 'No']

In [60]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25, random_state=42)

In [61]:
X_train.head()

      tip     sex  day    time  size  total_bill
115  3.50  Female  Sun  Dinner     2       17.31
181  5.65    Male  Sun  Dinner     2       23.33
225  2.50  Female  Fri   Lunch     2       16.27
68   2.01    Male  Sat  Dinner     2       20.23
104  4.08  Female  Sat  Dinner     2       20.92

In [62]:
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
le2 = LabelEncoder()
le3 = LabelEncoder()

In [63]:
X_train['sex'] = le1.fit_transform(X_train['sex'])
X_test['sex'] = le1.transform(X_test['sex'])

y_train = le2.fit_transform(y_train)
y_test = le2.transform(y_test)

X_train['time'] = le3.fit_transform(X_train['time'])
X_test['time'] = le3.transform(X_test['time'])

In [64]:
X_test.head()

      tip  sex   day  time  size  total_bill
24   3.18    1   Sat     0     2       19.82
6    2.00    1   Sun     0     2        8.77
153  2.00    1   Sun     0     4       24.55
211  5.16    1   Sat     0     4       25.89
198  2.00    0  Thur     1     2       13.00

In [65]:
y_train

array([0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 1])

In [66]:
X_train.head()

      tip  sex  day  time  size  total_bill
115  3.50    0  Sun     0     2       17.31
181  5.65    1  Sun     0     2       23.33
225  2.50    0  Fri     1     2       16.27
68   2.01    1  Sat     0     2       20.23
104  4.08    0  Sat     0     2       20.92

In [67]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('onehot', OneHotEncoder(drop='first'), [3])], remainder='passthrough')

In [68]:
import sys
np.set_printoptions(threshold=sys.maxsize)
X_train = ct.fit_transform(X_train)
X_test = ct.transform(X_test)

In [69]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

In [71]:
day_ct = ColumnTransformer(
	transformers=[('day_onehot', OneHotEncoder(handle_unknown='ignore'), [3])],
	remainder='passthrough'
)

X_train = day_ct.fit_transform(X_train)
X_test = day_ct.transform(X_test)

if hasattr(X_train, "toarray"):
	X_train = X_train.toarray()
	X_test = X_test.toarray()

gnb.fit(X_train, y_train)

GaussianNB()

In [72]:
y_pred = gnb.predict(X_test)

In [73]:
from sklearn.metrics import accuracy_score ,confusion_matrix, classification_report
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.7049180327868853
[[36  3]
 [15  7]]
              precision    recall  f1-score   support

           0       0.71      0.92      0.80        39
           1       0.70      0.32      0.44        22

    accuracy                           0.70        61
   macro avg       0.70      0.62      0.62        61
weighted avg       0.70      0.70      0.67        61